# Generated by Django 5.1.6 on 2025-02-27 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='name_en',
            field=models.CharField(default='none', max_length=200, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='categories',
            name='name_ru',
            field=models.CharField(default='none', max_length=200, null=True, verbose_name='Имя'),
        ),
    ]
